name: Build Gradle project

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
            arguments: build --scan
            working-directory: cybergari
