name: Build Gradle project

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run:
          | 
          cd cybergari
          ./gradlew build